### ISSUE TITLE
httpsconnectionpool error while using requests

### ISSUE THREAD

**Issue by varunmaitreya** [jython/frozen-mirror#103]
[![jython_python.png](https://s31.postimg.cc/8r3hwfnjv/jython_python.png)](https://postimg.cc/image/qtwknnjef/)
with python it works fine while with jython it gives strange issue. can anyone explain me as i'm new to jython

<pre style='color:#000000;background:#ffffff;'>varun<span style='color:#808030; '>@</span>varun<span style='color:#44aadd; '>-</span>X756UXK<span style='color:#808030; '>:</span><span style='color:#44aadd; '>~</span>$ jython
Jython <span style='color:#008000; '>2.7</span><span style='color:#808030; '>.</span><span style='color:#008c00; '>0</span> <span style='color:#808030; '>(</span>default<span style='color:#808030; '>:</span><span style='color:#008c00; '>9987</span><span style='color:#ffffff; background:#dd0000; font-weight:bold; font-style:italic; '>c746f838</span><span style='color:#808030; '>,</span> Apr <span style='color:#008c00; '>29</span> <span style='color:#008c00; '>2015</span><span style='color:#808030; '>,</span> <span style='color:#008c00; '>02</span><span style='color:#808030; '>:</span><span style='color:#008c00; '>25</span><span style='color:#808030; '>:</span><span style='color:#008c00; '>11</span><span style='color:#808030; '>)</span> 
<span style='color:#808030; '>[</span>Java HotSpot<span style='color:#808030; '>(</span>TM<span style='color:#808030; '>)</span> <span style='color:#008c00; '>64</span><span style='color:#44aadd; '>-</span>Bit Server VM <span style='color:#808030; '>(</span>Oracle Corporation<span style='color:#808030; '>)</span><span style='color:#808030; '>]</span> on java1<span style='color:#808030; '>.</span><span style='color:#008000; '>8.0</span><span style='color:#ffffff; background:#dd0000; font-weight:bold; font-style:italic; '>_171</span>
<span style='color:#400000; '>Type</span> <span style='color:#0000e6; '>"help"</span><span style='color:#808030; '>,</span> <span style='color:#0000e6; '>"copyright"</span><span style='color:#808030; '>,</span> <span style='color:#0000e6; '>"credits"</span> <span style='color:#800000; font-weight:bold; '>or</span> <span style='color:#0000e6; '>"license"</span> <span style='color:#800000; font-weight:bold; '>for</span> more information<span style='color:#808030; '>.</span>
<span style='color:#44aadd; '>>></span><span style='color:#44aadd; '>></span> <span style='color:#800000; font-weight:bold; '>import</span> requests
<span style='color:#44aadd; '>>></span><span style='color:#44aadd; '>></span> url <span style='color:#808030; '>=</span> <span style='color:#0000e6; '>'https://api.nal.usda.gov/ndb/V2/reports?ndbno=01009&amp;ndbno=45202763&amp;ndbno=35193&amp;type=b&amp;format=xml&amp;api_key=dcj2IihqQUe0XunKypsXv9vJBChxNg2Dud6er4Ae'</span>
<span style='color:#44aadd; '>>></span><span style='color:#44aadd; '>></span> requests<span style='color:#808030; '>.</span>request<span style='color:#808030; '>(</span><span style='color:#0000e6; '>"GET"</span><span style='color:#808030; '>,</span>url<span style='color:#808030; '>)</span>
<span style='color:#44aadd; '>/</span>home<span style='color:#44aadd; '>/</span>varun<span style='color:#44aadd; '>/</span>jython2<span style='color:#808030; '>.</span><span style='color:#008000; '>7.0</span><span style='color:#44aadd; '>/</span>Lib<span style='color:#44aadd; '>/</span>site<span style='color:#44aadd; '>-</span>packages<span style='color:#44aadd; '>/</span>urllib3<span style='color:#44aadd; '>/</span>util<span style='color:#44aadd; '>/</span>ssl_<span style='color:#808030; '>.</span>py<span style='color:#808030; '>:</span><span style='color:#008c00; '>331</span><span style='color:#808030; '>:</span> SNIMissingWarning<span style='color:#808030; '>:</span> An HTTPS request has been made<span style='color:#808030; '>,</span> but the SNI <span style='color:#808030; '>(</span>Subject Name Indication<span style='color:#808030; '>)</span> extension to TLS <span style='color:#800000; font-weight:bold; '>is</span> <span style='color:#800000; font-weight:bold; '>not</span> available on this platform<span style='color:#808030; '>.</span> This may cause the server to present an incorrect TLS certificate<span style='color:#808030; '>,</span> which can cause validation failures<span style='color:#808030; '>.</span> You can upgrade to a newer version of Python to solve this<span style='color:#808030; '>.</span> <span style='color:#800000; font-weight:bold; '>For</span> more information<span style='color:#808030; '>,</span> see https<span style='color:#808030; '>:</span><span style='color:#44aadd; '>//</span>urllib3<span style='color:#808030; '>.</span>readthedocs<span style='color:#808030; '>.</span>io<span style='color:#44aadd; '>/</span>en<span style='color:#44aadd; '>/</span>latest<span style='color:#44aadd; '>/</span>advanced<span style='color:#44aadd; '>-</span>usage<span style='color:#808030; '>.</span>html<span style='color:#696969; '>#ssl-warnings</span>
  warnings<span style='color:#808030; '>.</span>warn<span style='color:#808030; '>(</span>
<span style='color:#44aadd; '>/</span>home<span style='color:#44aadd; '>/</span>varun<span style='color:#44aadd; '>/</span>jython2<span style='color:#808030; '>.</span><span style='color:#008000; '>7.0</span><span style='color:#44aadd; '>/</span>Lib<span style='color:#44aadd; '>/</span>site<span style='color:#44aadd; '>-</span>packages<span style='color:#44aadd; '>/</span>urllib3<span style='color:#44aadd; '>/</span>util<span style='color:#44aadd; '>/</span>ssl_<span style='color:#808030; '>.</span>py<span style='color:#808030; '>:</span><span style='color:#008c00; '>130</span><span style='color:#808030; '>:</span> InsecurePlatformWarning<span style='color:#808030; '>:</span> A <span style='color:#074726; '>true</span> SSLContext <span style='color:#400000; '>object</span> <span style='color:#800000; font-weight:bold; '>is</span> <span style='color:#800000; font-weight:bold; '>not</span> available<span style='color:#808030; '>.</span> This prevents urllib3 <span style='color:#800000; font-weight:bold; '>from</span> configuring SSL appropriately <span style='color:#800000; font-weight:bold; '>and</span> may cause certain SSL connections to fail<span style='color:#808030; '>.</span> You can upgrade to a newer version of Python to solve this<span style='color:#808030; '>.</span> <span style='color:#800000; font-weight:bold; '>For</span> more information<span style='color:#808030; '>,</span> see https<span style='color:#808030; '>:</span><span style='color:#44aadd; '>//</span>urllib3<span style='color:#808030; '>.</span>readthedocs<span style='color:#808030; '>.</span>io<span style='color:#44aadd; '>/</span>en<span style='color:#44aadd; '>/</span>latest<span style='color:#44aadd; '>/</span>advanced<span style='color:#44aadd; '>-</span>usage<span style='color:#808030; '>.</span>html<span style='color:#696969; '>#ssl-warnings</span>
  warnings<span style='color:#808030; '>.</span>warn<span style='color:#808030; '>(</span>
Traceback <span style='color:#808030; '>(</span>most recent call last<span style='color:#808030; '>)</span><span style='color:#808030; '>:</span>
  <span style='color:#400000; '>File</span> <span style='color:#0000e6; '>"&lt;stdin>"</span><span style='color:#808030; '>,</span> line <span style='color:#008c00; '>1</span><span style='color:#808030; '>,</span> <span style='color:#800000; font-weight:bold; '>in</span> <span style='color:#44aadd; '>&lt;</span>module<span style='color:#44aadd; '>></span>
  <span style='color:#400000; '>File</span> <span style='color:#0000e6; '>"/home/varun/jython2.7.0/Lib/site-packages/requests/api.py"</span><span style='color:#808030; '>,</span> line <span style='color:#008c00; '>58</span><span style='color:#808030; '>,</span> <span style='color:#800000; font-weight:bold; '>in</span> request
    <span style='color:#800000; font-weight:bold; '>return</span> session<span style='color:#808030; '>.</span>request<span style='color:#808030; '>(</span>method<span style='color:#808030; '>=</span>method<span style='color:#808030; '>,</span> url<span style='color:#808030; '>=</span>url<span style='color:#808030; '>,</span> <span style='color:#44aadd; '>**</span>kwargs<span style='color:#808030; '>)</span>
  <span style='color:#400000; '>File</span> <span style='color:#0000e6; '>"/home/varun/jython2.7.0/Lib/site-packages/requests/sessions.py"</span><span style='color:#808030; '>,</span> line <span style='color:#008c00; '>508</span><span style='color:#808030; '>,</span> <span style='color:#800000; font-weight:bold; '>in</span> request
    resp <span style='color:#808030; '>=</span> self<span style='color:#808030; '>.</span>send<span style='color:#808030; '>(</span>prep<span style='color:#808030; '>,</span> <span style='color:#44aadd; '>**</span>send_kwargs<span style='color:#808030; '>)</span>
  <span style='color:#400000; '>File</span> <span style='color:#0000e6; '>"/home/varun/jython2.7.0/Lib/site-packages/requests/sessions.py"</span><span style='color:#808030; '>,</span> line <span style='color:#008c00; '>618</span><span style='color:#808030; '>,</span> <span style='color:#800000; font-weight:bold; '>in</span> send
    r <span style='color:#808030; '>=</span> adapter<span style='color:#808030; '>.</span>send<span style='color:#808030; '>(</span>request<span style='color:#808030; '>,</span> <span style='color:#44aadd; '>**</span>kwargs<span style='color:#808030; '>)</span>
  <span style='color:#400000; '>File</span> <span style='color:#0000e6; '>"/home/varun/jython2.7.0/Lib/site-packages/requests/adapters.py"</span><span style='color:#808030; '>,</span> line <span style='color:#008c00; '>506</span><span style='color:#808030; '>,</span> <span style='color:#800000; font-weight:bold; '>in</span> send
    <span style='color:#800000; font-weight:bold; '>raise</span> SSLError<span style='color:#808030; '>(</span>e<span style='color:#808030; '>,</span> request<span style='color:#808030; '>=</span>request<span style='color:#808030; '>)</span>
requests<span style='color:#808030; '>.</span>exceptions<span style='color:#808030; '>.</span>SSLError<span style='color:#808030; '>:</span> HTTPSConnectionPool<span style='color:#808030; '>(</span>host<span style='color:#808030; '>=</span><span style='color:#0000e6; '>'api.nal.usda.gov'</span><span style='color:#808030; '>,</span> port<span style='color:#808030; '>=</span><span style='color:#008c00; '>443</span><span style='color:#808030; '>)</span><span style='color:#808030; '>:</span> <span style='color:#400000; '>Max</span> retries exceeded <span style='color:#800000; font-weight:bold; '>with</span> url<span style='color:#808030; '>:</span> <span style='color:#44aadd; '>/</span>ndb<span style='color:#44aadd; '>/</span>V2<span style='color:#44aadd; '>/</span>reports?ndbno<span style='color:#808030; '>=</span><span style='color:#008c00; '>0100</span><span style='color:#ffffff; background:#dd0000; font-weight:bold; font-style:italic; '>9</span><span style='color:#44aadd; '>&amp;</span>ndbno<span style='color:#808030; '>=</span><span style='color:#008c00; '>45202763</span><span style='color:#44aadd; '>&amp;</span>ndbno<span style='color:#808030; '>=</span><span style='color:#008c00; '>35193</span><span style='color:#44aadd; '>&amp;</span><span style='color:#400000; '>type</span><span style='color:#808030; '>=</span>b<span style='color:#44aadd; '>&amp;</span>format<span style='color:#808030; '>=</span>xml<span style='color:#44aadd; '>&amp;</span>api_key<span style='color:#808030; '>=</span>dcj2IihqQUe0XunKypsXv9vJBChxNg2Dud6er4Ae <span style='color:#808030; '>(</span>Caused by SSLError<span style='color:#808030; '>(</span>SSLError<span style='color:#808030; '>(</span><span style='color:#008c00; '>1</span><span style='color:#808030; '>,</span> <span style='color:#0000e6; '>u'General SSLEngine problem (javax.net.ssl.SSLHandshakeException: General SSLEngine problem)'</span><span style='color:#808030; '>)</span><span style='color:#808030; '>,</span><span style='color:#808030; '>)</span><span style='color:#808030; '>)</span>
</pre>

**Comment by jeff5** [comment]
Luckily, it's giving us a clue that the missing element here is [SNI protocol](https://en.wikipedia.org/wiki/Server_Name_Indication) support, which it looks like the excellent @darjus added in 2016.

It would be worth trying 2.7.1 if you are able, since it contains that work.

Alternatively, there  work-arounds at [the URL in the helpful message](https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings).

**Comment by jeff5** [comment]
I'm reading this as now a downstream problem.
