### ISSUE TITLE
Can someone reauthorize AppVeyor with GitHub?

### ISSUE THREAD

**Issue by cclauss** [jython/frozen-mirror#139]
@jeff5 This might be an easier solution to #136  Is this something that you can try?

https://help.appveyor.com/discussions/problems/11287-the-build-phase-is-set-to-msbuild-mode-default-but-no-visual-studio-project-or-solution-files-were-found

**Comment by jeff5** [comment]
As noted on #136, this is mostly mysterious to me. @jimbaker or @darjus : do you have the keys to the CI kingdom?

**Comment by jeff5** [comment]
@darjus Thanks for having set up the CI way back.

Having learned a little now about CI (Travis CI anyway), I'm fairly sure these depend on your personal accounts with those services, Circle CI evaporated and AppVeyor has been returning false failures for ages so I have (I think) removed their hooks from this repo.

The Windows testing AppVeyor once provided us would be useful, so I'll re-instate it, if I can, but maybe using Azure pipelines as @jamesmudd suggested, and it appears CPython uses.

**Comment by jamesmudd** [comment]
I would be happy to do a bit more work to get Azure pipelines working properly if we decide its the way we want to go?  Think we would need a "Jython" account the demo work I did a while ago was using my account. I think its a good service and cross platform builds in one place seem simpler to me. By the way Travis now has Windows too https://docs.travis-ci.com/user/reference/windows/ so maybe we could try that?

**Comment by cclauss** [comment]
GitHub now has an Actions-based CI capability that I have been using quite successfully lately but I believe that the project would need to be in the beta program for GitHub actions.

**Comment by jeff5** [comment]
@cclauss I looked up Actions but the button shown in the [guide](https://help.github.com/en/articles/setting-up-continuous-integration-using-github-actions) is not there for any repo I've looked into. If I wander into GiutHub Marketplace, I'm offered a lot of gadgets that are Action-based.

@jamesmudd I found my way via Marketplace to Azure. It looks like I could log in there either as jeff5 or jython. I think we have the same rights to the jython organisation, so I expect it is the same for you. I was not offered jythontools where the mirror repo is.

I think we should, and shall, have the official jython repo under the jython organisation once 2.7.2 is out.

**Comment by cclauss** [comment]
I think you have to be accepted in the Beta and then on a repo that you have commit rights to for that button to show up.  I am in the Beta but that button does not show up on repos that I do not have commit rights to.

Azure Piplines is a good choice as well.

Unfortunately, I never did figure out how to __choco install ant__ inside of Travis Windows  :-(
