### ISSUE TITLE
Html sanitizer pip module

### ISSUE THREAD

**Issue by zaszlo** [jython/frozen-mirror#168]
I tried some html sanitizer modules but none of them was working.
It yields import errors, for htmllaundry it throws this:
```
Traceback (most recent call last):
  File "gombasz-json2md.py", line 6, in <module>
    from htmllaundry import sanitize
  File "C:\jython2.7.1\Lib\site-packages\htmllaundry\__init__.py", line 1, in <module>
    from htmllaundry.utils import sanitize
  File "C:\jython2.7.1\Lib\site-packages\htmllaundry\utils.py", line 3, in <module>
    from lxml import etree
```
Any hints on what tidy/sanitizer module should I use with jython?

**Comment by Stewori** [comment]
Looks like you should check if lxml can work with Jython. lxml is using Cython which wouldn't work with Jython. However, I *think* Cython is only optional: https://github.com/lxml/lxml/blob/9436948369d636d50355f7f679a0cfd7edc23044/setupinfo.py#L101 suggests it can be built without Cython. Maybe you would need to obtain a custom build of lxml with cython disabled.
