### ISSUE TITLE
Getting error “can't create package cache dir, 'cachedir/packages'” when trying to use Jython in Android

### ISSUE THREAD

**Issue by f24aalam** [jython/frozen-mirror#169]
I am using `org.python:jython-standalone:2.7.1` to run Python code inside Android application, as reference to [this][1] question, but I am getting an error 

> can't create package cache dir, 'cachedir/packages'

I am using gradle for installing Jython Standalone dependency

> implementation 'org.python:jython-standalone:2.7.1'

I also provided the Read\Write permission as I thought it could be helpful

Here is my code for Interpreted example

```
import org.python.core.PyInstance;
import org.python.core.PyObject;
import org.python.util.PythonInterpreter;

public class InterpreterExample {
    public PythonInterpreter interpreter = null;

    public InterpreterExample(){
        PythonInterpreter.initialize(System.getProperties(), System.getProperties(), new String[0]);
        this.interpreter = new PythonInterpreter();
    }

    void execfile(final String filename){
        this.interpreter.execfile(filename);
    }

    PyObject createFunction(final String functionName){
        return this.interpreter.get(functionName);
    }

    PyInstance createClass(final String className, final String opts){
        return (PyInstance)this.interpreter.eval(className + "(" + opts + ")");
    }
}
```
and I am using this class as

```
public void runScript(View view){
    InterpreterExample ie = new InterpreterExample();
    ie.execfile("hello.py");

    PyObject result = ie.createFunction("test").__call__();
    String strResult = (String) result.__tojava__(String.class);

    Toast.makeText(this, strResult, Toast.LENGTH_SHORT).show();
}
```

need a solution for this error, 
Thank You

  [1]: https://stackoverflow.com/questions/11120130/programming-android-apps-in-jython

**Comment by Stewori** [comment]
The answer you link is false for current Jython. I once answered a similar request on the mailing list: https://sourceforge.net/p/jython/mailman/message/36752389/

I would love to see Jython work on Android, but this just isn't feasible without significant additional development effort.
