### ISSUE TITLE
Installing 2.7.2rc1 on Java 11 causes an illegal reflective access warning

### ISSUE THREAD

**Issue by tysonite** [jython/frozen-mirror#171]
```
$ java -jar jython-installer-2.7.2rc1.jar -s -d jython
Performing silent installation
 10 %
 20 %
 30 %
 40 %
 50 %
 60 %
 70 %
Generating start scripts ...
Installing pip and setuptools
 90 %
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.io.StreamIO (file:/home/tysonite/jython/jython.jar) to field java.io.FilterOutputStream.out
WARNING: Please consider reporting this to the maintainers of org.python.core.io.StreamIO
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Java version:
```
$ java -showversion
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
```

**Comment by jeff5** [comment]
This is harmless, and all the best software does this, for example https://github.com/gradle/gradle/issues/6725 :)

We can't stop it in general, since we know no other way to satisfy an explicit request for a file handle, than to peek behind the scenes. But I think we could/should have suppressed it where we launch `ensurepip` in `JarInstaller.java`. It only takes an `--add-opens ...`, but it has to be contingent on the version.

**Comment by tysonite** [comment]
I see, thanks. 

Would it possible to suppress this warning programmatically? Like in [this case](https://github.com/tysonite/robotframework/runs/491363234?check_suite_focus=true#step:8:142), the system expects no output, but due to that issue, Jython prints warning and it would be not quite convinient to pass everywhere `--add-opens` option.

**Comment by jeff5** [comment]
The jython launcher (if you're not rolling your own java command) respects the environment variable `JAVA_OPTS`. Might that help?

For example on Windows PoSH I can write:
```
PS jython-trunk> $env:JAVA_OPTS="--add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED"
PS jython-trunk> dist\bin\jython -c "import os, sys; f = sys.stdin.fileno(); print os.isatty(f)"
True
```
Which otherwise produces the ugly warning from `os.isatty`.

**Comment by tysonite** [comment]
It works! Usage of `JAVA_OPTS` solves the issue with unexpected output in Robot tests. Thanks for suggestion.

**Comment by tysonite** [comment]
@jeff5, is there any standard way to get Java version in Jython?

E.g. on WSL/Linux with OpenJDK:
```
$ jython/bin/jython -c "import platform; print(platform.java_ver())"
('11.0.6', 'Ubuntu', ('OpenJDK 64-Bit Server VM', '11.0.6+10-post-Ubuntu-1ubuntu118.04.1', 'Ubuntu'), ('Linux', '4.4.0-18362-Microsoft', 'amd64'))
```

Or on Win with Oracle JDK 1.8:
```
D:\mak\projects>jython/bin/jython -c "import platform; print(platform.java_ver())"
('1.8.0_121', 'Oracle Corporation', ('Java HotSpot(TM) 64-Bit Server VM', '25.121-b13', 'Oracle Corporation'), ('Windows 10', '10.0', 'amd64'))
```

We are thinking about setting `JAVA_OPTS` automatically based on Java and Jython versions.

**Comment by jeff5** [comment]
I don't know about "standard" (as in the one obvious way) but that seems a good one. Unlike `os.name` etc., which I think is an old mistake (from when there was nothing else), it has one well-defined interpretation. At least the version number seems beyond doubt.

They appear to come straight from the (mostly guaranteed) Java system properties:
https://hg.python.org/jython/file/tip/Lib/platform.py#l873
