### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by tghjnjvg** [jython/frozen-mirror#172]
jython有没有能支持android的呀 或者改一改jython的源码让它支持android jython开源的吗 源码哪里看呢

**Comment by jeff5** [comment]
(According to Google Translate) @tghjnjvg wrote:
> Does jython support android or change the source code of jython to make it support android jython open source?
>

I've never tried this but I'm sure the answer is "no it doesn't". There is some discussion easily found with a search engine, of which this may be most helpful: https://wiki.python.org/moin/Android

This is helpful too: https://stackoverflow.com/questions/36356330/difference-between-bytecode-in-class-file-and-that-of-dex-file .

I think this is probably feasible, but a large piece of work for which we wouldn't have capacity at present.

**Comment by Stewori** [comment]
Once @jimbaker told me that the central issue is that Jython generates bytecode at runtime. Consequently, an Android Jython would have to dex and load it at runtime. Loading new classfiles at runtime is prohibited on Android AFAIK. @jeff5 I still wonder how hard it would be to let Jython do all the necessary things AOT. Sure, for some operations in Python this is inherently impossible, like `eval`, but I would imagine that a fair amount of programs do not depend on these operations. (The remaining part can eventually be covered by Python bytecode, c.f. https://github.com/jythontools/gsoc2015#python-bytecode-compiler.)

**Comment by jeff5** [comment]
@Stewori : I started to enumerate all the things that made this difficult, but eventually I retreated to "large piece of work".

I also concluded that the generation of (Dalvik VM byte-) code _dynamically_ is the main issue. I think you're exactly right that, there are times you can't have that, and the answer is to generate Python byte code and interpret it.
