### ISSUE TITLE
installing gensim

### ISSUE THREAD

**Issue by ali3assi** [jython/frozen-mirror#94]
Hello,

how can install gensim using jython 2.7.1 whcih is already worked well on my session in SSH linux server.

Thank you in adavance

**Comment by Stewori** [comment]
It looks like gensim is using NumPy and SciPy extensively. At least I find plenty of results if I search for numpy or scipy in the gensim repository and it doesn't look like these were just optional imports for acceleration. While you can get some portion of NumPy working with [JyNI](http://www.jyni.org), SciPy is currently not feasible. So, I'm afraid running gensim on Jython is currently not possible.

**Comment by TamouzeAssi** [comment]
Sir @Stewori 
Thank you for your reply, do you know please if there is any other library can help in installing or including these two libraries?
Thank you

**Comment by Stewori** [comment]
You can use [JEP](https://github.com/ninia/jep) or [Py4J](https://github.com/bartdag/py4j), but these yield no compatibility with Jython. These libs launch a CPython interpreter in parallel to the JVM.
You really cannot run gensim on Jython (before JyNI properly matures) unless you would rewrite half of the code or so to use Java-API for what is usually done with NumPy or SciPy e.g. using [jblas](https://github.com/mikiobraun/jblas). (In that case make sure to share that work!)
