### ISSUE TITLE
History of API changes for Jython

### ISSUE THREAD

**Issue by lvc** [jython/frozen-mirror#95]
Hi,

I'd like to share report on API changes and backward compatibility for Jython: https://abi-laboratory.pro/java/tracker/timeline/jython-standalone/

BC — binary compatibility
SC — source compatibility

The report is generated according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2 by the https://github.com/lvc/upstream-tracker-4j tool.

The tool checks only packages described in the documentation: http://www.jython.org/javadoc/

Hope it will be helpful for users and maintainers of the library.

Thank you.

![jython-standalone-1](https://user-images.githubusercontent.com/1517837/32402251-e88f78c0-c130-11e7-8483-d41bbf103cc6.png)

![jython-standalone-2](https://user-images.githubusercontent.com/1517837/32402250-e8711a60-c130-11e7-89b3-f38c7e998f2c.png)

**Comment by jeff5** [comment]
Interesting gadget, thanks. 2.7 obviously must differ a lot from 2.5, but it is fair to say we don't define a subset of visible symbols as the stable API, in the way CPython has. Hence drift in the visible methods is just a matter of self-discipline. Sometimes things are visible just so we can use them from another package.

I'm surprised to find some of the unit tests are in there. That's a flaw in how we build for release I think.

> The tool checks only packages described in the documentation: http://www.jython.org/javadoc/

So, does adding Javadoc to an existing method make it appear new at that point? I'm quite likely to do this where I do any work to understand existing code.

**Comment by lvc** [comment]
> So, does adding Javadoc to an existing method make it appear new at that point?

No. It checks all classes and methods in packages listed in http://www.jython.org/javadoc/. A method appears new only if it's added to a `*.class` file.

I've just restricted the analysis to the list of classes described in docs: https://abi-laboratory.pro/java/tracker/timeline/jython-standalone/

Thank you.
